### ISSUE TITLE
Attachment漏洞无效

### ISSUE THREAD

**Issue by admin-del** [White-hua/Apt_t00ls#13]
![image](https://user-images.githubusercontent.com/105182827/225254684-aa839558-1f51-4cbc-8ef7-071a4daede2b.png)
我抓包后分析，发现Attachment这个漏洞无法上传文件，请问是否是我写错了？

**Comment by White-hua** [comment]
python代码问题建议百度

**Comment by admin-del** [comment]
大佬你好，我问的不是代码的问题，这个是我抓包后发现这个漏洞是从这个路径上传的问题，我用自己写的代码发现根本上传不了，这个漏洞是否存在？我测试了网上很多的系统，都没法上传

**Comment by admin-del** [comment]
大佬你好，我问的不是代码的问题，这个是我抓包后发现这个漏洞是从这个路径上传的问题，我用自己写的代码发现根本上传不了，这个漏洞是否存在？我测试了网上很多的系统，都没法上传

**Comment by White-hua** [comment]
payload有问题  已经更新release
