### ISSUE TITLE
macOS M1 报错

### ISSUE THREAD

**Issue by LcxSg** [White-hua/Apt_t00ls#18]
<img width="865" alt="截屏2023-07-01 17 09 24" src="https://github.com/White-hua/Apt_t00ls/assets/37261737/7279a4d9-a20e-49c2-a24b-56a076250bb4">

Macbook Pro M1 Monterey 12.6
执行jar报错，师傅们能帮忙看看吗

**Comment by stop-bullshit** [comment]
oracle jdk  openjdk 好像缺少组件

**Comment by LcxSg** [comment]
谢谢，更换JDK后问题解决
