### ISSUE TITLE
Error: Could not find or load main class Main

### ISSUE THREAD

**Issue by studyVVVV** [White-hua/Apt_t00ls#8]
启动命令：java -jar apt_tools-jar-with-dependencies.jar
错误信息：
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Error: Could not find or load main class Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by MasterLover** [comment]
请使用包含javafx的jdk例如 oracle jdk8
